# Generated by Django 6.1.1 on 2026-10-03 10:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\- ]{7,20}$', 'Enter a valid phone number (digits, spaces, - and optional leading +).')])),
                ('address', models.TextField()),
                ('reason', models.TextField(verbose_name='Why do you want this pet?')),
                ('previous_pet_experience', models.BooleanField(default=False, verbose_name='Have you owned a pet before?')),
                ('message', models.TextField(blank=True, verbose_name='Additional message')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to='pets.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['Pending', 'Approved'])), fields=('user', 'pet'), name='unique_active_request_per_user_pet')],
            },
        ),
    ]
